### ISSUE TITLE
Erdi meg nincs fent githubon.

### ISSUE THREAD

**Issue by KGergo88** [KGergo88/RDB_Diplomaterv#1]

**Comment by sodreg** [comment]
Mar fenn van.

**Comment by KGergo88** [comment]
Le tudod zarni az issue-t vagy csak en?

**Comment by sodreg** [comment]
Nem látok lezáró gombot vagy lehetőséget.

**Comment by KGergo88** [comment]
Alul a comment mellett van ilyen close issue gomb nekem.
